### ISSUE TITLE
Differences in dgps and our site

### ISSUE THREAD

**Issue by keshav1245** [co16353sidak/PB-Project#23]
DIFFERENCES

1. TOP BAR AND NAV BAR
- [ ] On top bar dgps have options like screen reader, feedback and font increase decrease , language select and colour theme select.

- [x] On the nav bar dgps have a search bar along with advance search option. - Search implemented

- [x] Navbar design is slightly different on show - Fixed in latest commit

2. CAROUSEL
- [ ] in dgps Web site we have a carousel having a sample image , image of the press and image of map with locations of the  press. 
- [x] Along with that , there is a box displaying ministers of Gujarat above on the carousel - Fixed by #34 

3. WELCOME SECTION
- [ ] The welcome section in dgps site have a moving horizontal text on the top and also have a section for latest news and events on its right, which is not the case with our site .

- [ ] A link for Gazette name change birth change is provided below in the welcome section 

4. FEATURE SECTION
- [x] here dgps site have a grid layout along with a map on its right showing the location of the department. - map is implemented now.

- [x] our site is not having a map - Site has map in contact section.

- [ ] next comes their sample images and video section which is missing on our site

5. FOOTER
- [x] Footer elements are different - Made in accordance with dips

**Comment by theNaut1lus** [comment]
Check latest commit for changes, by mistake didn't edit changes on my branch but on main branch.
don't follow what I did.

**Comment by keshav1245** [comment]
footer in Organisation structure and apprentice scheme is having bullet elements in it 
Secondly no content for apprentice scheme page
